# Generated by Django 5.0.4 on 2024-06-01 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QurilishTashkiloti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_company', models.DateField(auto_now_add=True)),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.hudud')),
            ],
        ),
        migrations.CreateModel(
            name='QurilishBinosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('maydoni', models.FloatField(default=0)),
                ('qavat', models.IntegerField(default=0)),
                ('parkovka', models.IntegerField(default=0)),
                ('lift', models.IntegerField(default=0)),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.hudud')),
                ('qurilish_tashkiloti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.qurilishtashkiloti')),
            ],
        ),
    ]
